# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
          
      - name: Install rush
        run: npm install -g @microsoft/rush

      - uses: actions/cache@v2
        id: cache
        with:
         path: "common/temp"
         key: ${{ runner.os }}-node-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
         restore-keys: |
            ${{ runner.os }}-node-pnpm-

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install --bypass-policy
        env:
         CI: ""
                          
      - name: Build all packages
        run: node common/scripts/install-run-rush.js rebuild --verbose
        
      - run: echo "Test file !!! " > test.txt
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: test.txt
          channel: rush-test
